title: Soupbowl
subtitle: Ramblings of a DevOps Nerd
description: >-
  Personal blog for Casey - a back-end developer specialising in PHP, primarily for WordPress developments. 
  Primarily a source of niche setup guides, cool Raspberry Pi builds, and general ranting.
baseurl: ""
url: "https://www.soupbowl.io"
footnote: Hello from London.

exclude: ['.github', 'README.md', 'LICENSE', 'docker-compose.yml', 'Gemfile.lock', 'Gemfile']

theme: jekyll-bootstrap-theme
bootstrap:
  header_pages:
    - projects/index.md
    - blog/index.html
  social_links:
    twitter: https://twitter.com/TheAlmightyWord
    github:  https://github.com/soup-bowl
author:
  name: soup-bowl
  email: code@soupbowl.io

paginate: 5
paginate_path: "/blog/page/:num/"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
  - jemoji
